import React,{useEffect,useRef,useState} from "react"; import {createRoot} from "react-dom/client"; import "./styles.css";

const KEY="singalways-library-v2";
const readSongs=()=>{try{return JSON.parse(localStorage.getItem(KEY)||"[]")}catch{return[]}};
const saveSongs=s=>localStorage.setItem(KEY,JSON.stringify(s));
const randomSegment=duration=>{const d=Math.max(1,Number(duration)||60),length=Math.min(60,Math.max(30,d));const maxStart=Math.max(0,d-length);const start=maxStart?Math.random()*maxStart:0;return{start,end:Math.min(d,start+length)}};

function App(){const [songs,setSongs]=useState(readSongs),[song,setSong]=useState(null),[segment,setSegment]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[playing,setPlaying]=useState(false),[recording,setRecording]=useState(false),[importMode,setImportMode]=useState("upload"),[message,setMessage]=useState("");const audio=useRef(null),rec=useRef(null),stream=useRef(null),chunks=useRef([]);
const load=()=>setSongs(readSongs()); useEffect(()=>{load()},[]);
const start=s=>{setError("");setMessage("");const seg=randomSegment(s.duration);setSong(s);setSegment({...seg,url:s.audioUrl});setPlaying(false)};
useEffect(()=>{if(audio.current&&segment){audio.current.currentTime=segment.start;audio.current.play().then(()=>setPlaying(true)).catch(()=>{});}},[segment]);
const upload=async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError("");setMessage("");try{const title=prompt("Título de la canción",file.name.replace(/\.[^.]+$/,""))||file.name;const meta=await new Promise(resolve=>{const a=document.createElement("audio");a.preload="metadata";a.onloadedmetadata=()=>{const d=Number.isFinite(a.duration)?a.duration:0;URL.revokeObjectURL(a.src);resolve(d)};a.onerror=()=>{URL.revokeObjectURL(a.src);resolve(0)};a.src=URL.createObjectURL(file)});const audioUrl=URL.createObjectURL(file);const s={id:crypto.randomUUID(),title,artist:"",duration:meta,audioUrl,source:"upload"};const next=[s,...songs];setSongs(next);saveSongs(next);setMessage("Canción importada en este dispositivo.");}catch(x){setError(x.message)}finally{setBusy(false);e.target.value=""}};
const youtube=async()=>{const url=prompt("Pega el enlace de YouTube");if(!url)return;setBusy(true);setError("");setMessage("");try{const r=await fetch("/api/youtube",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({url})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"No se pudo obtener el audio");if(!d.audio_url)throw new Error("El servicio no devolvió un audio reproducible");const s={id:crypto.randomUUID(),title:d.title||"YouTube song",artist:d.artist||"",duration:Number(d.duration)||60,audioUrl:d.audio_url,source:"youtube",sourceUrl:url};const next=[s,...songs];setSongs(next);saveSongs(next);setMessage("Canción de YouTube añadida sin usar R2.");}catch(e){setError(e.message)}finally{setBusy(false)}};
const mic=async()=>{if(recording){rec.current?.stop();return}try{stream.current=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];const r=new MediaRecorder(stream.current);r.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);r.onstop=()=>{stream.current?.getTracks().forEach(t=>t.stop());setRecording(false)};rec.current=r;r.start();setRecording(true)}catch(e){setError("No se pudo activar el micrófono: "+e.message)}};
return <div className="app"><header><div className="brand">🎤 <span>SingAlways</span></div><button className="ghost" onClick={load}>↻</button></header>
<main><section className="hero"><div><p className="kicker">KARAOKE · SIN R2</p><h1>Canta <em>cualquier</em> canción.</h1><p className="sub">Los archivos importados se guardan localmente en este navegador. YouTube usa el servicio de audio configurado, sin almacenamiento R2.</p></div><div className="orb">♫</div></section>
{error&&<div className="alert">{error}</div>}{message&&<div className="notice">{message}</div>}
<section className="import"><div className="tabs"><button className={importMode==="upload"?"active":""} onClick={()=>setImportMode("upload")}>Importar archivo</button><button className={importMode==="youtube"?"active":""} onClick={()=>setImportMode("youtube")}>YouTube</button></div>{importMode==="upload"?<label className="drop"><input type="file" accept="audio/*" onChange={upload}/><strong>+ Añadir canción</strong><span>MP3, WAV, M4A, OGG… · se queda en tu dispositivo</span></label>:<button className="youtube" onClick={youtube} disabled={busy}>▶ Añadir desde YouTube</button>}</section>
<section><div className="section-title"><h2>Biblioteca</h2><span>{songs.length} canciones</span></div>{songs.length?<div className="grid">{songs.map(s=><button className="song" key={s.id} onClick={()=>start(s)}><div className="cover">♫</div><div><b>{s.title}</b><small>{s.artist||"Sin artista"} · {Math.round(s.duration)}s · {s.source==="youtube"?"YouTube":"Local"}</small></div><span>→</span></button>)}</div>:<div className="empty">Todavía no hay canciones. Importa la primera arriba.</div>}</section>
</main>
{song&&segment&&<div className="modal"><div className="player"><button className="close" onClick={()=>{audio.current?.pause();setSong(null);setSegment(null)}}>×</button><p className="kicker">ROUND</p><h2>{song.title}</h2><p className="segment">Fragmento {Math.round(segment.start)}s → {Math.round(segment.end)}s</p><div className="wave"><span>♪</span><span>♫</span><span>♩</span><span>♬</span><span>♪</span></div><audio ref={audio} src={segment.url} controls onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} /><div className="actions"><button className="primary" onClick={()=>{if(playing)audio.current.pause();else audio.current.play()}}>{playing?"❚❚ Pausar":"▶ Cantar"}</button><button className={recording?"recording":"secondary"} onClick={mic}>{recording?"● Grabando…":"🎙 Micrófono"}</button></div><p className="hint">Tu voz se captura localmente durante la ronda. La app no la sube al servidor.</p></div></div>}
{busy&&<div className="loading">Procesando…</div>}</div>}; createRoot(document.getElementById("root")).render(<App/>);