import React,{useEffect,useRef,useState} from "react"; import {createRoot} from "react-dom/client"; import "./styles.css";

const api=async(url,options={})=>{const r=await fetch(url,options);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Request failed");return d};

function App(){const [songs,setSongs]=useState([]),[song,setSong]=useState(null),[segment,setSegment]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[playing,setPlaying]=useState(false),[recording,setRecording]=useState(false),[importMode,setImportMode]=useState("upload"),[message,setMessage]=useState("");const audio=useRef(null),rec=useRef(null),stream=useRef(null),chunks=useRef([]);

const load=()=>api("/api/songs").then(d=>setSongs(d.songs||[])).catch(e=>setError(e.message));
useEffect(()=>{load()},[]);
const start=async s=>{setError("");setMessage("");setBusy(true);try{const d=await api("/api/segment/"+s.id);setSong(s);setSegment(d.segment);setPlaying(false)}catch(e){setError(e.message)}finally{setBusy(false)}};
useEffect(()=>{if(audio.current&&segment){audio.current.currentTime=segment.start;audio.current.play().then(()=>setPlaying(true)).catch(()=>{});}},[segment]);

const upload=async e=>{const file=e.target.files?.[0];if(!file)return;const fd=new FormData();fd.append("audio",file);const title=prompt("Título de la canción",file.name.replace(/\.[^.]+$/,""))||file.name;fd.append("title",title);const meta=await new Promise(resolve=>{const a=document.createElement("audio");a.preload="metadata";a.onloadedmetadata=()=>resolve(Number.isFinite(a.duration)?a.duration:0);a.onerror=()=>resolve(0);a.src=URL.createObjectURL(file)});fd.append("duration",String(meta));setBusy(true);setError("");try{await api("/api/import",{method:"POST",body:fd});setMessage("Canción importada.");await load()}catch(x){setError(x.message)}finally{setBusy(false)}};
const youtube=async()=>{const url=prompt("Pega el enlace de YouTube");if(!url)return;setBusy(true);setError("");try{await api("/api/youtube",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({url})});setMessage("Canción añadida desde YouTube.");await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
const mic=async()=>{if(recording){rec.current?.stop();return}try{stream.current=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];const r=new MediaRecorder(stream.current);r.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);r.onstop=()=>{stream.current?.getTracks().forEach(t=>t.stop());setRecording(false)};rec.current=r;r.start();setRecording(true)}catch(e){setError("No se pudo activar el micrófono: "+e.message)}};

return <div className="app"><header><div className="brand">🎤 <span>SingAlways</span></div><button className="ghost" onClick={load}>↻</button></header>
<main><section className="hero"><div><p className="kicker">KARAOKE · ANY SONG</p><h1>Canta <em>cualquier</em> canción.</h1><p className="sub">Importa audio o añade una URL de YouTube. Cada ronda recibe un fragmento aleatorio de 30–60 segundos.</p></div><div className="orb">♫</div></section>
{error&&<div className="alert">{error}</div>}{message&&<div className="notice">{message}</div>}
<section className="import"><div className="tabs"><button className={importMode==="upload"?"active":""} onClick={()=>setImportMode("upload")}>Importar archivo</button><button className={importMode==="youtube"?"active":""} onClick={()=>setImportMode("youtube")}>YouTube</button></div>{importMode==="upload"?<label className="drop"><input type="file" accept="audio/*" onChange={upload}/><strong>+ Añadir canción</strong><span>MP3, WAV, M4A, OGG…</span></label>:<button className="youtube" onClick={youtube} disabled={busy}>▶ Añadir desde YouTube</button>}</section>
<section><div className="section-title"><h2>Biblioteca</h2><span>{songs.length} canciones</span></div>{songs.length?<div className="grid">{songs.map(s=><button className="song" key={s.id} onClick={()=>start(s)}><div className="cover">♫</div><div><b>{s.title}</b><small>{s.artist||"Sin artista"} · {Math.round(s.duration)}s</small></div><span>→</span></button>)}</div>:<div className="empty">Todavía no hay canciones. Importa la primera arriba.</div>}</section>
</main>
{song&&segment&&<div className="modal"><div className="player"><button className="close" onClick={()=>{audio.current?.pause();setSong(null);setSegment(null)}}>×</button><p className="kicker">ROUND</p><h2>{song.title}</h2><p className="segment">Fragmento {Math.round(segment.start)}s → {Math.round(segment.end)}s</p><div className="wave"><span>♪</span><span>♫</span><span>♩</span><span>♬</span><span>♪</span></div><audio ref={audio} src={segment.url} controls onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)}/><div className="actions"><button className="primary" onClick={()=>{if(playing)audio.current.pause();else audio.current.play()}}>{playing?"❚❚ Pausar":"▶ Cantar"}</button><button className={recording?"recording":"secondary"} onClick={mic}>{recording?"● Grabando…":"🎙 Micrófono"}</button></div><p className="hint">Tu voz se captura localmente durante la ronda. La app no la sube al servidor.</p></div></div>}
{busy&&<div className="loading">Procesando…</div>}</div>}; createRoot(document.getElementById("root")).render(<App/>);