import React,{useEffect,useState} from "react"; import {createRoot} from "react-dom/client"; import "./styles.css";

const KEY="singalways-library-v2";
const readSongs=()=>{try{return JSON.parse(localStorage.getItem(KEY)||"[]")}catch{return[]}};
const saveSongs=s=>localStorage.setItem(KEY,JSON.stringify(s));
const segmentFor=(duration,savedStart=null)=>{const d=Math.max(1,Number(duration)||60),length=Math.min(60,Math.max(30,d)),maxStart=Math.max(0,d-length);const raw=Number(savedStart);const start=Number.isFinite(raw)?Math.min(maxStart,Math.max(0,raw)):(maxStart?Math.random()*maxStart:0);return{start,end:Math.min(d,start+length)}};
const youtubeId=url=>{try{const u=new URL(url);if(u.hostname==="youtu.be")return u.pathname.slice(1).split("/")[0];if(u.pathname.startsWith("/shorts/"))return u.pathname.split("/")[2];return u.searchParams.get("v")}catch{return null}};
const youtubeEmbed=(url,start,end)=>{const id=youtubeId(url);return id?`https://www.youtube.com/embed/${encodeURIComponent(id)}?start=${Math.floor(start)}&end=${Math.ceil(end)}&autoplay=1&rel=0`:null};

function App(){const [songs,setSongs]=useState(readSongs),[song,setSong]=useState(null),[segment,setSegment]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[recording,setRecording]=useState(false),[importMode,setImportMode]=useState("upload"),[message,setMessage]=useState("");const [playing,setPlaying]=useState(false);const rec=React.useRef(null),stream=React.useRef(null),chunks=React.useRef([]);

const load=async()=>{try{const local=readSongs().filter(s=>s.source!=="youtube");const r=await fetch("/api/songs");const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"No se pudo cargar SongSave");setSongs([...local,...(d.songs||[])]);}catch(e){setSongs(readSongs());setError(e.message)}};
useEffect(()=>{load()},[]);

const start=s=>{setError("");setMessage("");const duration=s.source==="youtube"?60:s.duration;const seg=segmentFor(duration,s.segmentStart);if(s.source==="youtube"&&!youtubeId(s.sourceUrl)){setError("El enlace de YouTube no es válido.");return}setSong(s);setSegment(seg);setPlaying(false)};

const upload=async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError("");setMessage("");try{const title=prompt("Título de la canción",file.name.replace(/\.[^.]+$/,""))||file.name;const meta=await new Promise(resolve=>{const a=document.createElement("audio");a.preload="metadata";a.onloadedmetadata=()=>{const d=Number.isFinite(a.duration)?a.duration:0;URL.revokeObjectURL(a.src);resolve(d)};a.onerror=()=>{URL.revokeObjectURL(a.src);resolve(0)};a.src=URL.createObjectURL(file)});const audioUrl=URL.createObjectURL(file);const s={id:crypto.randomUUID(),title,artist:"",duration:meta,audioUrl,source:"upload"};const local=readSongs().filter(x=>x.source!=="youtube");const next=[s,...local];setSongs(next);saveSongs(next);setMessage("Canción importada en este dispositivo.");}catch(x){setError(x.message)}finally{setBusy(false);e.target.value=""}};

const youtube=async()=>{const url=prompt("Pega el enlace de YouTube");if(!url)return;setBusy(true);setError("");setMessage("");try{const r=await fetch("/api/youtube",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({url})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"No se pudo guardar la canción en SongSave");const s={id:d.id||crypto.randomUUID(),title:d.title||"YouTube song",artist:d.artist||"",duration:60,source:"youtube",sourceUrl:d.sourceUrl||url,segmentStart:Number(d.segment?.start)||0};const local=readSongs().filter(x=>x.source!=="youtube");setSongs([s,...local,...songs.filter(x=>x.source==="youtube"&&x.id!==s.id)]);setMessage("Canción guardada en SongSave.");}catch(e){setError(e.message)}finally{setBusy(false)}};

const mic=async()=>{if(recording){rec.current?.stop();return}try{stream.current=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];const r=new MediaRecorder(stream.current);r.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);r.onstop=()=>{stream.current?.getTracks().forEach(t=>t.stop());setRecording(false)};rec.current=r;r.start();setRecording(true)}catch(e){setError("No se pudo activar el micrófono: "+e.message)}};

return <div className="app"><header><div className="brand">🎤 <span>SingAlways</span></div><button className="ghost" onClick={load}>↻</button></header>
<main><section className="hero"><div><p className="kicker">KARAOKE · SONGSAVE D1</p><h1>Canta <em>cualquier</em> canción.</h1><p className="sub">Las canciones de YouTube se guardan en SongSave y se reproducen con el reproductor oficial de YouTube. Los archivos locales siguen en este dispositivo.</p></div><div className="orb">♫</div></section>
{error&&<div className="alert">{error}</div>}{message&&<div className="notice">{message}</div>}
<section className="import"><div className="tabs"><button className={importMode==="upload"?"active":""} onClick={()=>setImportMode("upload")}>Importar archivo</button><button className={importMode==="youtube"?"active":""} onClick={()=>setImportMode("youtube")}>YouTube</button></div>{importMode==="upload"?<label className="drop"><input type="file" accept="audio/*" onChange={upload}/><strong>+ Añadir canción</strong><span>MP3, WAV, M4A, OGG… · se queda en tu dispositivo</span></label>:<button className="youtube" onClick={youtube} disabled={busy}>▶ Añadir desde YouTube</button>}</section>
<section><div className="section-title"><h2>Biblioteca</h2><span>{songs.length} canciones</span></div>{songs.length?<div className="grid">{songs.map(s=><button className="song" key={s.id} onClick={()=>start(s)}><div className="cover">♫</div><div><b>{s.title}</b><small>{s.artist||"Sin artista"} · {s.duration?Math.round(s.duration)+"s":"YouTube"} · {s.source==="youtube"?"YouTube":"Local"}</small></div><span>→</span></button>)}</div>:<div className="empty">Todavía no hay canciones. Importa la primera arriba.</div>}</section>
</main>
{song&&segment&&<div className="modal"><div className="player"><button className="close" onClick={()=>{setPlaying(false);setSong(null);setSegment(null)}}>×</button><p className="kicker">ROUND</p><h2>{song.title}</h2><p className="segment">Fragmento {Math.round(segment.start)}s → {Math.round(segment.end)}s</p><div className="wave"><span>♪</span><span>♫</span><span>♩</span><span>♬</span><span>♪</span></div>{song.source==="youtube"?<>{youtubeEmbed(song.sourceUrl,segment.start,segment.end)?<iframe className="youtube-player" title={song.title} src={youtubeEmbed(song.sourceUrl,segment.start,segment.end)} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen />:<div className="alert">No se pudo crear el reproductor de YouTube.</div>}<p className="hint">YouTube controla la reproducción del vídeo. El fragmento empieza y termina en los segundos indicados.</p></>:<audio src={song.audioUrl} controls autoPlay onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} /> }<div className="actions">{song.source!=="youtube"&&<button className="primary" onClick={()=>setPlaying(!playing)}>{playing?"❚❚ Pausar":"▶ Cantar"}</button>}<button className={recording?"recording":"secondary"} onClick={mic}>{recording?"● Grabando…":"🎙 Micrófono"}</button></div><p className="hint">Tu voz se captura localmente durante la ronda. La app no la sube al servidor.</p></div></div>}
{busy&&<div className="loading">Procesando…</div>}</div>}; createRoot(document.getElementById("root")).render(<App/>);